image: microsoft/dotnet:1.0.0-preview2-sdk

before_script:
  - export BUILD_DIR="$(realpath $(pwd))"
  - export NUGET_PACKAGES="$BUILD_DIR/.nuget"

cache:
  paths:
    - "./.nuget"
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - dotnet restore
    - . ./build-all.sh
  artifacts:
    paths:
      - "./*/*/bin"
      - "./*/*/obj"
      - "./*/*/project.lock.json"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - dotnet restore
    - . ./test-all.sh
  artifacts:
    paths:
      - "./*/*/bin"
      - "./*/*/obj"
      - "./*/*/project.lock.json"

#integrationtest-job:
#  stage: test
#  dependencies:
#    - build-job
#  script:
#    - dotnet restore
#    - dotnet test --integration
#  artifacts:
#    paths:
#      - "./*/*/bin"
#      - "./*/*/obj"
#      - "./*/*/project.lock.json"

deploy-job:
  stage: deploy
  script:
    - dotnet restore
    - . ./publish-all.sh
  artifacts:
    paths:
       - "./*/*/bin/*/*.nupkg"

