image: microsoft/dotnet:latest

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

#before_script:
#  - apt-get update

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    paths:
      - bin/
      - obj/
      - project.lock.json

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - dotnet test test/Service.Tests
      #- echo "TotalInstructionCoverage:" `cat target/site/jacoco/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
  artifacts:
    paths:
      - bin/
      - obj/
      - project.lock.json

#integrationtest-job:
#  stage: test
#  dependencies:
#    - build-job
#  script:
#    - dotnet test
#    - echo "TotalInstructionCoverage:" `cat target/site/jacoco-it/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
#  artifacts:
#    paths:
#      - bin/
#      - obj/
#      - project.lock.json

deploy-job:
  stage: deploy
  script:
    - dotnet publish
  artifacts:
    paths:
      - "bin/Debug/*.nupkg"
      - "bin/Release/*.nupkg"
