image: microsoft/dotnet:latest

cache:
  paths:
    - "./.nuget"
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

before_script:
  - export BUILD_DIR="`pwd`"
  - export DOTNET_PARAMS="--packages $BUILD_DIR/.nuget"

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - eval "dotnet restore $DOTNET_PARAMS"
    - . ./build-all.sh
  artifacts:
    paths:
      - "./*/*/bin"
      - "./*/*/obj"
      - "./*/*/project.lock.json"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - eval "dotnet restore $DOTNET_PARAMS"
    - . ./test-all.sh
      #- echo "TotalInstructionCoverage:" `cat target/site/jacoco/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
  artifacts:
    paths:
      - "./*/*/bin"
      - "./*/*/obj"
      - "./*/*/project.lock.json"

#integrationtest-job:
#  stage: test
#  dependencies:
#    - build-job
#  script:
#    - eval "dotnet restore $DOTNET_PARAMS"
#    - dotnet test
#    - echo "TotalInstructionCoverage:" `cat target/site/jacoco-it/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
#  artifacts:
#    paths:
#      - "./*/*/bin"
#      - "./*/*/obj"
#      - "./*/*/project.lock.json"

deploy-job:
  stage: deploy
  script:
    - eval "dotnet restore $DOTNET_PARAMS"
    - . ./publish-all.sh
  artifacts:
    paths:
       - "./*/*/bin/*/*.nupkg"

